### PR TITLE
fix #5 Compiler warning: “initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute”

### LINKED ISSUE #5: Compiler warning: “initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute”
While building the project on my Arch machine,  the compiler emits
The following error/warning:

`
    error: initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (17 chars into 16 available) [-Werror=unterminated-string-initialization]
`
which I believe was in the src/socketio.c file.

### PR DESCRIPTION
**Pull request by lsahmed**
There was a warning error because the array exactly has space for 16 actual characters 
`
static char const hexdigits_lower[16] = "0123456789abcdef";
`
But every string in C automatically adds a hidden \0 at the end, so that means the array has to be 17 bytes long. 
So I just let the compiler infer the size instead of increasing one byte.

### CODE REVIEW

File: src/socketio.c [hunk 1]
```diff
@@ -635,4 +635,4 @@ void socketioCleanup()
 void socketioLog()
 {
   printl(LOG_INFO, "SEND: buffer: %ld packet: %ld globalbuffer: %ld\n", sendPacketVars.buffersize, sendPacketVars.packetsize, sendPacketVars.globalbuffersize);
-}
\ No newline at end of file
+}
```
Comment (vimpop) [inline src/socketio.c:638]: can this change be reverted?

**Review by vimpop — CHANGES_REQUESTED** [review]
A change in socketioLog() function has to be reverted otherwise the commit looks fine.
Thanks for the fix!

File: src/socketio.c (hunk 1 above)
Comment (lsahmed) [reply src/socketio.c:638]: Apologies for that, sure on it.
